package compulsory1.generators;

import java.io.IOException;

/**
 * This script generates input files that can be read by other methods such as
 * {@link compulsory1.management.TestClient} and {@link compulsory1.generators.Vizualizer}.
 * All files are generated by Random generator with a seed meaning they should produce the same
 * result whenever they are ran.
 * 
 * @author Olav Bakken og Martin Vatshelle
 */
public class Generate {
	
	//script to generate random intput
	public static void main(String arg[]) throws IOException {
		GenerateUniform gen1 = new GenerateUniform(12345L);
		GenerateUniform gen2 = new GenerateUniform(23456L);
		GenerateNormal gen3 = new GenerateNormal(15, 0, 34567L);
		GenerateNormal gen4 = new GenerateNormal(50, 0, 45678L);
		GenerateNormal gen5 = new GenerateNormal(15, 100, 56789L);
		GenerateBinarySlow gen6 = new GenerateBinarySlow(10, 0, 56789L);
		gen1.generate(100, 200, "input/01.in");
		gen2.generate(100, 1000, "input/02.in");
		gen3.generate(100, 1000, 1, "input/03.in");
		gen4.generate(100, 1000, 2, "input/04.in");
		gen5.generate(100, 1000, 1, "input/05.in");
		gen6.generate(1000, "input/06.in");
	}
}
